### ISSUE TITLE
Mau Nanya 

### ISSUE THREAD

**Issue by Tanaka9531** [amiruldev20/kiapi#1]
Itu Api Aku Kan ? Sudah Ku Private Kok Masih Bisa Kesebar ?
![Screenshot (172)](https://user-images.githubusercontent.com/73052642/119447898-c4b78580-bd5a-11eb-9682-2c942611572f.png)

**Comment by amiruldev20** [comment]
ini api nemu dah ada 2mingguan via dorking, niatnya mau ambil example kerangkanya fitur mau aku ubah. di install di heroku eror jdi yaudah gk kulanjutkn

**Comment by Tanaka9531** [comment]
Itu Sc Lama Sih Sc Baru Baru Aja Selesai :D

**Comment by Tanaka9531** [comment]
Lu Mastah Kan :)

**Comment by Tanaka9531** [comment]
Wa Donk Ia Kali Mau Tanya
